package com.sunagatov.memora.backend.domain

import java.time.Instant

data class MemoraItem(
    val id: String,
    val mindraftId: String,
    val sourceType: SourceType,
    val telegramUserId: Long?,
    val telegramChatId: Long?,
    val telegramMessageId: Long?,
    val telegramFileId: String?,
    val telegramFileUniqueId: String?,
    val rawInputText: String?,
    val rawTranscript: String?,
    val aiTitle: String,
    val aiCleanedText: String,
    val aiType: ItemType,
    val aiCategory: String,
    val aiSubcategory: String,
    val aiSubsubcategory: String,
    val aiPriority: Priority,
    val title: String,
    val cleanedText: String,
    val type: ItemType,
    val category: String,
    val subcategory: String,
    val subsubcategory: String,
    val priority: Priority,
    val status: ItemStatus,
    val failureStage: String? = null,
    val failureReason: String? = null,
    val retryCountTranscription: Int = 0,
    val retryCountAi: Int = 0,
    val createdAt: Instant,
    val updatedAt: Instant,
    val approvedAt: Instant? = null,
    val deletedAt: Instant? = null,
    val rejectedAt: Instant? = null
)
